config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    collection do
      get 'search'
    end
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :ratings
    
    validates :title, presence:true
    validates :director, presence:true
    validates :release_year, presence:true

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
      @movies = Movie.all
    end
  
    def new
      @movie = Movie.new
    end
  
    def create
      @movie = Movie.new(movie_params)
      if @movie.save
        redirect_to @movie, notice: 'Movie was successfully created.'
      else
        render :new
      end
    end
  
    def show
      @movie = Movie.find(params[:id])
    end
  
    def edit
      @movie = Movie.find(params[:id])
    end
  
    def update
      @movie = Movie.find(params[:id])
      if @movie.update(movie_params)
        redirect_to @movie, notice: 'Movie was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @movie = Movie.find(params[:id])
      @movie.destroy
      redirect_to movies_url, notice: 'Movie was successfully destroyed.'
    end

    def search
        @movies = Movie.where("title LIKE ? OR director LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
      end
  
      def rate
        @movie = Movie.find(params[:id])
        @rating = @movie.ratings.new(score: params[:score])
        if @rating.save
          redirect_to @movie, notice: 'Movie was successfully rated.'
        else
          redirect_to @movie, alert: 'Rating failed.'
        end
      end

    private
      def movie_params
        params.require(:movie).permit(:title, :director, :release_year)
      end
  end
  

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController


    def index
        @movie = Movie.find(params[:movie_id])
        @ratings = @movie.ratings
      end

    def new
        @movie = Movie.find(params[:movie_id])
        @rating = @movie.ratings.build
      end

    def create
        @movie = Movie.find(params[:movie_id])
        @rating = @movie.ratings.build(rating_params)

        if @rating.save
            redirect_to movie_ratings_path(@movie), notice: 'Rating was successfully created.'
        else
            render :new
        end
    end

    private

    def rating_params
        params.require(:rating).permit(:score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Listing Movies</h1>

<%= form_tag search_movies_path, method: :get do %>
    <%= label_tag :query, "Search:" %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search" %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Director</th>
      <th>Release Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.director %></td>
        <td><%= movie.release_year %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/search.html.erb
<h1>Search Results</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Director</th>
      <th>Release Year</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.director %></td>
        <td><%= movie.release_year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Listing', movies_path %>

app/views/ratings/index.html.erb
<h1>Listing Ratings for <%= @movie.title %></h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to movie', @movie %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= form_for [@movie, @rating], url: movie_ratings_path(@movie) do |f| %>
  <%= f.label :score %>
  <%= f.number_field :score, min: 1, max: 10 %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', @movie %>
<%= link_to 'Show Ratings', movie_ratings_path(@movie), class: 'button' %>